name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bark-ml:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: virtualenv -p python3 ./utils/venv  --system-site-packages
      - name: Entering the virtual python environment..
        run: . ./utils/venv/bin/activate
      - name: Installing additional Python packages..
        run: pip install tf2_gnn spektral tensorflow-addons==0.11.2 graph-nets==1.1.0 ray==1.0.0 xviz-avs==0.1.0a4
      - name: Building..
        run: bazel build //...